version: 2
project_name: bufexplorer

env_files:
  # GoReleaser requires an API token with the 'repo' scope selected to deploy
  # the artifacts to GitHub. You can create one here
  # https://github.com/settings/tokens/new.
  github_token: ./github_token

    #builds:
    #  - skip: true

    #source:
    #  name_template: '{{ .ProjectName }}-{{ .Version }}'.
    #  format: "zip"
    #  files:
    #    - plugin/bufexplorer.vim
    #    - doc/bufexplorer.txt
    #    - LICENSE

archives:
  - #
    name_template: "{{ .ProjectName }}-{{ .Version }}"
    format: zip
    files:
      - plugin/bufexplorer.vim
      - doc/bufexplorer.txt
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - README

release:
  draft: false
  replace_existing_draft: true
